language: node_js
node_js:
- '7'
after_success:
- bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
env:
  global:
    secure: EEF9zzzOp6rkcu7bRLoeuxwkl+xOFanOm7/TLxsxnHdTC9CTbGB9JTO14tkoHr3YcfpsP50v7wIDaCcFsqYcV7RF3WcwjduAxKRzRbctJ4PPIDyrs2LN9KeQbn5pBn3PMoNj07a4+lPBxDFwyTyaT7Z1znPARDLkhfE/0Or3aa2gaU8vOAOFqptXkPmi2bD5HkfH3FsDu1Gh1wq5ZkozpZcmKCwlAOudecLGolOCp9oit4jc5sO4mZOzG5w1MyB8daSuJyARhl/G4VwiklhqhQ3g39q7yhIzYnJDIWLnFvCdxJd1DL8xDhWOAUxWd73v/EU+bFoxD1k/DOVEkKj0zzPqm8gduLxkawKfDvnLcommXw//Ls6n6K/USe9Hp1B2LLiEqjQoChTwwwu9ugWe2VMxvPKspCvyhW8ZmcGYVv4Z2ontbr7EXepoLadPpcH7s+Jg9rUEPutcWcsh5PiTf0otRl8WqUlNZjP4jYAg8msQCGgd79W0W6wx9rCUpROaUpBmQhccpOTXyUIa+LSe5yyqR1cnPc7zDj615Ec2dA/0EFPLIAMm3GPRn+iW9sP+EhIa0Da1ObhsoJoLsnjozJuTR/DD9L2mIHwzC41VZRSNvkrHj9ZOO5/BrNSjv53mmV5ZWszqpaHGac2ZOL1f8RS7HugD6f5H2AU0RUqgEBc=
